misc: Collect-and-check considers 'win64' warnings non-pertinent
For now. Due to dozens of:

Error: win64 - D:\a\etlegacy\etlegacy\src\qcommon\q_shared.c(1563,10): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data [D:\a\etlegacy\etlegacy\build\ui.vcxproj]

Type warnings.